openapi: 3.0.0
info:
  title: MEN REST API
  description: MongoDB ExpressJS NodeJS REST API
  version: 1.0.0
servers:
  - url: http://localhost:8000/
    description: Localhost development server
  - url: https://smsj-men-restapi.herokuapp.com/api/
    description: Heroku remote server
components:
  securitySchemes:
    ApiKeyAuth: # arbitrary name for the security scheme
      type: apiKey
      in: header # can be "header", "query" or "cookie"
      name: auth-token

  schemas:
    Reservation:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        where:
          type: string
          enum:
            - cafe
            - bar
            - diner
        phone:
          type: string
paths:
  /reservation/create:
    post:
      summary: Create a new reservation
      description: Create a new reservation and save to database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Reservation"

      responses:
        201:
          description: Reservation created succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  _id:
                    type: string
